from .order import DistributorOrderApproveView, DistributorOrderDeleteView, DistributorOrderDetailView, DistributorOrderListView
from .dealer import DealerCreateView, DealerUpdateView, DealerListView, DealerDeleteView, DealerRelationView
from .payment import DistributorPaymentApproveView, DistributorPaymentListView, DistributorPaymentDealerDetailView, DistributorPaymentDealerListView