# Generated by Django 2.0.5 on 2019-05-09 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=25, verbose_name='Ad')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi')),
            ],
            options={
                'verbose_name': 'Marka',
                'verbose_name_plural': 'Markalar',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=50, verbose_name='Ad')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
            },
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=50, verbose_name='Ad')),
                ('content', models.TextField(verbose_name='Açıklama')),
                ('address', models.TextField(verbose_name='Adres')),
                ('phone', models.CharField(max_length=11, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Posta')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yetkili')),
                ('staff', models.ManyToManyField(blank=True, related_name='dealers', related_query_name='dealer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bayi',
                'verbose_name_plural': 'Bayiler',
                'permissions': [('manage_dealer', 'Bayi yönetim izni')],
            },
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=50, verbose_name='Ad')),
                ('content', models.TextField(verbose_name='Açıklama')),
                ('address', models.TextField(verbose_name='Adres')),
                ('phone', models.CharField(max_length=11, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Posta')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yetkili')),
                ('dealers', models.ManyToManyField(blank=True, related_name='distributors', related_query_name='distributor', to='project.Dealer')),
                ('staff', models.ManyToManyField(blank=True, related_name='distributors', related_query_name='distributor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Distribütör',
                'verbose_name_plural': 'Distribütörler',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_transfered', models.BooleanField(default=False, verbose_name='Nakliye Tamamlandı')),
                ('order_cancelled', models.BooleanField(default=False, verbose_name='Sipariş İptal Edildi')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Sipariş Tarihi')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Sipariş Güncellenme Tarihi')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Dealer', verbose_name='Bayi')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Distributor', verbose_name='Distribütör')),
            ],
            options={
                'verbose_name': 'Sipariş',
                'verbose_name_plural': 'Siparişler',
                'permissions': [('manage_order', 'Sipariş yönetim izni')],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_count', models.PositiveIntegerField(verbose_name='Ürün Adedi')),
                ('item_price', models.FloatField(verbose_name='Ürün Fiyatı')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_items', to='project.Order', verbose_name='Sipariş')),
            ],
            options={
                'verbose_name': 'Sipariş Edilen Ürün',
                'verbose_name_plural': 'Sipariş Edilen Ürünler',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Miktar')),
                ('payment_accepted', models.CharField(choices=[('K', 'KABUL EDİLDİ'), ('R', 'RED EDİLDİ'), ('I', 'İPTAL EDİLDİ'), ('B', 'BEKLEMEDE')], default='B', max_length=1, verbose_name='Ödeme Kabülü')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Ödeme Tarihi')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Dealer', verbose_name='Bayi')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Distributor', verbose_name='Distribütör')),
            ],
            options={
                'verbose_name': 'Ödeme',
                'verbose_name_plural': 'Ödemeler',
                'permissions': [('manage_payment', 'Ödeme yönetim izni')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=50, verbose_name='Ad')),
                ('content', models.TextField(verbose_name='Açıklama')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi')),
                ('active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('price', models.FloatField(verbose_name='Fiyat')),
                ('stock_count', models.PositiveIntegerField(verbose_name='Stok Adedi')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%D/', verbose_name='Resim')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Brand', verbose_name='Marka')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Distributor', verbose_name='Distribütör')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'ordering': ['-created'],
                'permissions': [('manage_product', 'Ürün yönetim izni')],
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Product', verbose_name='Ürün'),
        ),
        migrations.AddField(
            model_name='category',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='products', related_query_name='product', to='project.Product'),
        ),
    ]
