from .approve import DistributorPaymentApproveView
from .detail import DistributorPaymentDealerDetailView
from .list import DistributorPaymentListView
from .detail_list import DistributorPaymentDealerListView